repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: ['black']
        args: [--line-length=120]
      - id: isort
        args: ["--profile", "black"]
        name: isort
        entry: isort
        language: python
        types: [python]
      - id: pycln
        name: pycln
        entry: pycln
        language: python
        types: [python]